{% set name = "zndraw" %}
{% set version = "0.5.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zndraw-{{ version }}.tar.gz
  sha256: 51740c5b406eef53aaceedf26a970db001f6d8709e27f2d751ad5b4d78a19bb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - ase >=3.0.0,<4.0.0
    - typer >=0.0.0,<1.0.0
    - flask >=2.0.0,<3.0.0
    - tqdm >=4.0.0,<5.0.0
    - flask-socketio >=5.0.0,<6.0.0
    - networkx >=3.0.0,<4.0.0
    - pydantic >=2.0.0,<3.0.0
    - python-socketio >=5.11.0,<6.0.0
    - plotly >=5.0.0,<6.0.0
    - pandas >=2.0.0,<3.0.0
    - celery >=5.0.0,<6.0.0
    - sqlalchemy >=2.0.0,<3.0.0
    - redis-py >=5.0.0,<6.0.0
    - splines >=0.3.0,<0.4.0
    - znsocket >=0.2.7,<0.3.0
    - znjson >=0.2.4,<0.3.0
    - requests

test:
  imports:
    - zndraw
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zincware/ZnDraw
  summary: Display and Edit Molecular Structures and Trajectories in the Browser.
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
